import { UmrahPackage } from "../../types";

export const umrahPackage1: UmrahPackage = {
  id: "umrah-14d-economy",
  titleBn: "১৪ দিনের ইকোনমি উমরাহ্ প্যাকেজ",
  titleEn: "14 Days Economy Umrah Package",
  badgeBn: "জনপ্রিয় ইকোনমি",
  badgeEn: "Popular Economy",
  durationBn: "১৪ দিন / ১৩ রাত",
  durationEn: "14 Days / 13 Nights",
  makkahHotelBn: "৩ স্টার মানসম্মত হোটেল (৮০০ মিটার)",
  makkahHotelEn: "3-Star Standard Hotel (800m)",
  makkahDistanceBn: "৮০০ মিটার (হাঁটা দূরত্ব)",
  makkahDistanceEn: "800 Meters (Walking Distance)",
  madinahHotelBn: "৩ স্টার হোটেল (৬০০ মিটার)",
  madinahHotelEn: "3-Star Hotel (600m)",
  madinahDistanceBn: "৬০০ মিটার",
  madinahDistanceEn: "600 Meters",
  foodBn: "তিন বেলা বাংলা খাবার (ক্যাটারিং)",
  foodEn: "3 Times Bengali Catering Food",
  transportBn: "জেদ্দা-মক্কা-মদিনা লাক্সারি এসি বাস",
  transportEn: "Jeddah-Makkah-Madinah Luxury AC Bus",
  ziyaraBn: "মক্কা ও মদিনার সকল ঐতিহাসিক দর্শনীয় স্থান",
  ziyaraEn: "All Historical Ziyara Sites in Makkah & Madinah",
  visaAndTicketBn: "উমরাহ্ ভিসা, ইন্স্যুরেন্স ও এয়ার টিকিটসহ",
  visaAndTicketEn: "Includes Umrah Visa, Insurance & Air Ticket",
  priceBDT: 145000,
  featured: true,
  image:
    "https://images.unsplash.com/photo-1591604466107-ec97de577aff?auto=format&fit=crop&w=800&q=80",
  inclusionsBn: [
    "এয়ার টিকিট (ঢাকা-জেদ্দা-ঢাকা)",
    "উমরাহ্ ভিসা",
    "হোটেল সুবিধা",
    "জিয়ারাহ সার্ভিস",
    "৩ বেলা খাবার",
    "এসি ট্রান্সপোর্ট",
  ],
  inclusionsEn: [
    "Air Ticket (Dhaka-Jeddah-Dhaka)",
    "Umrah Visa",
    "Hotel Accommodation",
    "Ziyarah Service",
    "3 Meals Daily",
    "AC Transport",
  ],
};
