import { UmrahPackage } from '../../types';

export const umrahPackage2: UmrahPackage = {
  id: 'umrah-14d-deluxe',
  titleBn: '১৪ দিনের ডিলাক্স ৪-স্টার উমরাহ্ প্যাকেজ',
  titleEn: '14 Days Deluxe 4-Star Umrah Package',
  badgeBn: 'প্রিমিয়াম ৪-স্টার',
  badgeEn: 'Premium 4-Star',
  durationBn: '১৪ দিন / ১৩ রাত',
  durationEn: '14 Days / 13 Nights',
  makkahHotelBn: '৪-স্টার হোটেল (৩০০ মিটার - ইব্রাহিম খলিল রোড)',
  makkahHotelEn: '4-Star Hotel (300m - Ibrahim Khalil Road)',
  makkahDistanceBn: '৩০০ মিটার (৩ মিনিট হাঁটা পথ)',
  makkahDistanceEn: '300 Meters (3 Min Walk)',
  madinahHotelBn: '৪-স্টার হোটেল (২০০ মিটার - কেন্দ্রীয় এরিয়া)',
  madinahHotelEn: '4-Star Hotel (200m - Central Area)',
  madinahDistanceBn: '২০০ মিটার',
  madinahDistanceEn: '200 Meters',
  foodBn: 'উন্নত বুফে / বিশেষ বাংলা খাবার',
  foodEn: 'Premium Buffet & Quality Meals',
  transportBn: 'প্রাইভেট বা ভিআইপি হাই-ক্লাস কোচ',
  transportEn: 'Private / VIP High Class Coach',
  ziyaraBn: 'অভিজ্ঞ মোয়াল্লেমসহ গাইড করা জিয়ারা',
  ziyaraEn: 'Guided Ziyara with Experienced Moallem',
  visaAndTicketBn: 'ডিরেক্ট ফ্লাইট টিকিট ও বায়োমেট্রিক ভিসা',
  visaAndTicketEn: 'Direct Flight Ticket & Biometric Visa',
  priceBDT: 175000,
  featured: true,
  image: 'https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80',
  inclusionsBn: ['ডাইরেক্ট এয়ার টিকিট', 'ভিআইপি ভিসা প্রসেসিং', '৪-স্টার হোটেল', 'বিশেষ বুফে খাবার', 'হাইস্পিড ট্রান্সপোর্ট', 'প্রতি হাজীর জন্য জমজম পানি ও উপহার'],
  inclusionsEn: ['Direct Air Ticket', 'VIP Visa Processing', '4-Star Hotels', 'Buffet Meals', 'High Speed Transport', 'Zamzam Water & Gift Kit'],
};
