import { UmrahPackage } from '../../types';

export const umrahPackage3: UmrahPackage = {
  id: 'umrah-21d-ramadan',
  titleBn: 'পবিত্র রমজান শরীফ ২১ দিনের বিশেষ উমরাহ্ প্যাকেজ',
  titleEn: '21 Days Holy Ramadan Special Umrah Package',
  badgeBn: 'রমজান স্পেশাল',
  badgeEn: 'Ramadan Special',
  durationBn: '২১ দিন / ২০ রাত',
  durationEn: '21 Days / 20 Nights',
  makkahHotelBn: 'হারামের সন্নিকটে ৪-স্টার মানসম্মত হোটেল',
  makkahHotelEn: '4-Star Hotel Near Haram Outer Courtyard',
  makkahDistanceBn: '৪০০ মিটার',
  makkahDistanceEn: '400 Meters',
  madinahHotelBn: 'মসজিদে নববীর খুব কাছে ৪-স্টার হোটেল',
  madinahHotelEn: '4-Star Hotel Close to Prophet Mosque',
  madinahDistanceBn: '২৫০ মিটার',
  madinahDistanceEn: '250 Meters',
  foodBn: 'সেহরি ও ইফতারসহ ৩ বেলা খাস ব্যবস্থা',
  foodEn: 'Sehri, Iftar & Dinner Full Support',
  transportBn: 'মক্কা-মদিনা এসি ভিআইপি বাস সার্ভিস',
  transportEn: 'Makkah-Madinah AC VIP Bus Service',
  ziyaraBn: 'লাইলাতুল কদর ও রমজানের বিশেষ আমল গাইডেন্স',
  ziyaraEn: 'Laylatul Qadr & Special Ramadan Guidance',
  visaAndTicketBn: 'রমজান ভিসা প্রসেসিং ও কনফার্মড টিকেট',
  visaAndTicketEn: 'Ramadan Visa Processing & Confirmed Ticket',
  priceBDT: 235000,
  featured: false,
  image: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&w=800&q=80',
  inclusionsBn: ['রমজান উমরাহ্ ভিসা', 'সেহরি ও ইফতার', 'হারামের কাছে হোটেল', 'অভিজ্ঞ মোয়াল্লেম', 'বিশেষ দোয়া পরিচালনা'],
  inclusionsEn: ['Ramadan Umrah Visa', 'Sehri & Iftar Included', 'Close Haram Hotel', 'Experienced Moallem', 'Dua Guidance'],
};
